# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Modern Engineering
email: jon@jonyonker.com
description: > # this means to ignore newlines until "baseurl:"
  Jon Yonker's Software Engineering Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.jonyonker.com" # the base hostname & protocol for your site
twitter_username: TWITTER
github_username:  jyonker

# Build settings
markdown: kramdown
